

### model
model_name_or_path: Note2Chat/models/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all


### dataset
dataset: final_version_single_turn_sampling_summary_plan

template: qwen
cutoff_len: 4096
overwrite_cache: true

### output
output_dir: Note2Chat/models/my_single_turn_sft_sampling
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
learning_rate: 5.0e-5
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

flash_attn: fa2
